/* Generated by Yosys 0.12+45 (git sha1 UNKNOWN, gcc 8.3.1 -fPIC -Os) */

module test_macro(clk, rst, y, p_end, x0, x1, x2, x3, x4, x5, x6, x7, x8, x9);
  input clk;
  wire \p[0] ;
  wire \p[1] ;
  wire \p[2] ;
  wire \p[3] ;
  wire \p[4] ;
  wire \p[5] ;
  wire \p[6] ;
  wire \p[7] ;
  wire \p[8] ;
  output p_end;
  input rst;
  input [31:0] x0;
  input [30:0] x1;
  input [30:0] x2;
  input [30:0] x3;
  input [30:0] x4;
  input [30:0] x5;
  input [30:0] x6;
  input [30:0] x7;
  input [30:0] x8;
  input [30:0] x9;
  input y;
  spm spm_01 (
    .clk(clk),
    .p(\p[1] ),
    .rst(rst),
    .x({ \p[0] , x1 }),
    .y(\p[0] )
  );
  spm spm_02 (
    .clk(clk),
    .p(\p[2] ),
    .rst(rst),
    .x({ x2[30], \p[1] , x2[29:0] }),
    .y(\p[1] )
  );
  spm spm_03 (
    .clk(clk),
    .p(\p[3] ),
    .rst(rst),
    .x({ x3[30:29], \p[2] , x3[28:0] }),
    .y(\p[2] )
  );
  spm spm_04 (
    .clk(clk),
    .p(\p[4] ),
    .rst(rst),
    .x({ x4[30:28], \p[3] , x4[27:0] }),
    .y(\p[3] )
  );
  spm spm_05 (
    .clk(clk),
    .p(\p[5] ),
    .rst(rst),
    .x({ x5[30:27], \p[4] , x5[26:0] }),
    .y(\p[4] )
  );
  spm spm_06 (
    .clk(clk),
    .p(\p[6] ),
    .rst(rst),
    .x({ x6[30:26], \p[5] , x6[25:0] }),
    .y(\p[5] )
  );
  spm spm_07 (
    .clk(clk),
    .p(\p[7] ),
    .rst(rst),
    .x({ x7[30:25], \p[6] , x7[24:0] }),
    .y(\p[6] )
  );
  spm spm_08 (
    .clk(clk),
    .p(\p[8] ),
    .rst(rst),
    .x({ x8[30:24], \p[7] , x8[23:0] }),
    .y(\p[7] )
  );
  spm spm_end_0 (
    .clk(clk),
    .p(p_end),
    .rst(rst),
    .x({ x9[30:23], \p[8] , x9[22:0] }),
    .y(\p[8] )
  );
  spm spm_start_0 (
    .clk(clk),
    .p(\p[0] ),
    .rst(rst),
    .x(x0),
    .y(y)
  );
endmodule
